### ISSUE TITLE
投稿詳細のパラメータについて

### ISSUE THREAD

**Issue by Hirochon** [Hirochon/Shappar#106]
![Screenshot from 2020-03-15 18-38-05](https://user-images.githubusercontent.com/50178851/76699007-29556a00-66ec-11ea-9bf5-5aac00f162c3.png)

上記画像のようになりました。
エンドポイントは以下です。
- `/api/v1/posts/{post_id}/`

**Comment by fujiya228** [comment]
ありがとうございます！
二点ほど質問です。

- keyが日本語なのが気になるんですが、変えるの厳しいですか？笑
- voted_monthは何を表してますか？（投票された日時？投票者の誕生月？）

よろしくお願いします！

**Comment by Hirochon** [comment]
お疲れ様ですー。

- Key英語変換可能です！(ageのKeyどうするか悩みどころ)
- 投票者の誕生月ですー

**Comment by fujiya228** [comment]
- ageに関しては0-10,10-20みたいな感じでどうですか？
- 誕生月了解です。
今後も大きく変更が加わるとは思うので、一旦日本語で書き換えます。

**Comment by Hirochon** [comment]
その表記いいですね！

書き換えはできたのですが、developにプルリク送っておきましょうか？

![Screenshot from 2020-03-15 22-40-00](https://user-images.githubusercontent.com/50178851/76702552-fe7c0d80-670d-11ea-836a-61105dc8af0f.png)

**Comment by fujiya228** [comment]
お！ありがとうございます！
おねがいします！
