### ISSUE TITLE
投稿削除のパラメータについて

### ISSUE THREAD

**Issue by Hirochon** [Hirochon/Shappar#109]
![Screenshot from 2020-03-15 18-47-48](https://user-images.githubusercontent.com/50178851/76699171-fca25200-66ed-11ea-970d-38b5609802ab.png)

上記のように実装
- エンドポイント：`/api/v1/posts/{post_id}/`
- HTTPメソッド：`DELETE`

**Comment by fujiya228** [comment]
了解しました！
変更しておきます！
