### ISSUE TITLE
ユーザごとのページのエンドポイントについて

### ISSUE THREAD

**Issue by Hirochon** [Hirochon/Shappar#13]
ユーザごとのページ(例えばマイページや投稿する時)のエンドポイントは、Swaggarでは{userID}と書いてたけど、そこは{不変のUUID}か{ユーザーが変更可能なuserID}のどちらが良い？？

※ちなみにAmazonS3(ストレージサービス)で画像を保存する時のディレクトリ先は、ユーザの変更に影響されたくないから、UUIDにするつもり！

**Comment by fujiya228** [comment]
UUIDでいいと思います～
ただ、userIDがユニークならuserIDのほうがアクセスするときとかにわかりやすくていいかとも思います～

**Comment by Hirochon** [comment]
返信ありがとうございます。

なるほど〜。userIDはユニークの設定にしています！
ですがユーザ本人が編集可能な設定にしているので、S3の方ではUUIDにしようと思っています。

マイページにおいては、userID,UUIDのどちらでもエンドポイントに設定できる状態にしておいたので、とりあえずuserIDにしておきましょうか？

**Comment by fujiya228** [comment]
OKです！
S3はUUID
マイページのAPIエンドポイントはuserIDで行きましょう！

**Comment by Hirochon** [comment]
> S3はUUID
> マイページのAPIエンドポイントはuserIDで行きましょう！

では上記の形で実装します！クローズしときますね〜
