### ISSUE TITLE
マイページのjsonのGETレスポンスに関して

### ISSUE THREAD

**Issue by Hirochon** [Hirochon/Shappar#14]
本来 @fujiya228 がSwaggarで下記のようにGETのjsonレスポンスを指定してくれてました！

```json:本来のマイページのGET.json
{
  "id": 1,
  "name": "sumple_user_name",
  "usersID": "sample_user_001",
  "text": "text text text text text text text",
  "iconURL": "http://example.com/iconURL",
  "homeImageURL": "http://example.com/homeImageURL"
}
```

だけどユーザアカウントのモデルをリレーションシップにてマイページモデルを作成した関係で、下記のようにuserにて階層ができてしまいます。

```json:実装時のマイページのGET.json
{
    "user": {
        "id": "UUID",
        "username": "sample_user_001",
        "usernonamae": "sumple_user_name",
        "iconimage": "http://example.com/iconURL"
    },
    "introduction": "text text text text text text text",
    "homeimage": "http://example.com/homeImageURL"
}
```

これでも構わないですか？？確認よろしくお願いします！
※補足:jsonレスポンスのKeyに関してはまた話し合いましょう。

**Comment by fujiya228** [comment]
フロント側で処理する分には問題ないです！
APIを公開するときにあまり階層深くならないように！
と思ってそうしているので大丈夫です！

Keyの名前に関して了解です！
※ケバブケースやキャメルケースなどのあたりもルールとして決めておきましょう！

**Comment by Hirochon** [comment]
階層は同感ですね。
了解です！

> ケバブケースやキャメルケースなどのあたりもルールとして決めておきましょう！

そのような命名規則の概念があることは初知りでした...。

とりあえず《マイページのjsonのGETレスポンスに関して》は解決したので、クローズしても構いませんか？

**Comment by fujiya228** [comment]
OKです！クローズしておきます！

**Comment by Hirochon** [comment]
以下のような事を言っていましたが...
> ユーザアカウントのモデルをリレーションシップにてマイページモデルを作成した関係で、下記のようにuserにて階層ができてしまいます。
>```json:response.json
>{
>    "user": {
>        "id": "UUID",
>        "username": "sample_user_001",
>        "usernonamae": "sumple_user_name",
>        "iconimage": "http://example.com/iconURL"
>    },
>    "introduction": "text text text text text text text",
>    "homeimage": "http://example.com/homeImageURL"
>}
>```

当初の🔻コチラのようなレスポンスの形式で実装することができたので、プルリクしておきました！

```json:response.json
{
  "id": "UUID",
  "usernnoamae": "sumple_user_name",
  "username": "sample_user_001",
  "introduction": "text text text text text text text",
  "iconimage": "http://example.com/iconURL",
  "homeImage": "http://example.com/homeImageURL"
}
```
