### ISSUE TITLE
Publicページでの、投稿検索機能について

### ISSUE THREAD

**Issue by fujiya228** [Hirochon/Shappar#16]
検索機能では、stringで検索クエリをリクエストする予定なのですが、実装できそうでしょうか？
また、検索機能としてその他に実装できそうな機能などはありますでしょうか？

**Comment by Hirochon** [comment]
問題ないです。是非とも検索機能は実装していきたいですね！

ユーザの登録時に性別や年齢の情報も集めているので、検索時に以下のようなフィルタリングも実装していきたいですね！

- 男のみ/女のみ ※その他と無回答は両方見れる形?
- それ以下/20代のみ/30代のみ/40代のみ/それ以上...　※それ以上それ以下の区切りをどこでつけるかは要相談？

**Comment by fujiya228** [comment]
了解です！
一旦、他のサービスで絞り込み方を探してみて、
その上でもう一度話し合いたいと思います。

APIのプロジェクトに追加してここは閉じますね！
