### ISSUE TITLE
マイページの投稿が未投票の時の表示が正しく反映されていない

### ISSUE THREAD

**Issue by fujiya228** [Hirochon/Shappar#268]
他人のマイページへ訪れた時、その他人の投稿におけるvotedが全てtrueになっている？

未投票の場合はfalseになっているとありがたい

**Comment by Hirochon** [comment]
@fujiya228 バグ発見ありがとうございます！

**Comment by Hirochon** [comment]
## 問題点
- メイン投稿一覧表示機能とマイページユーザー投稿済み投稿一覧表示機能のシリアライザで使用が異なる
- ビューにて渡す引数が異なる

## 修正点
- [x] マイページのユーザー投稿済み投稿一覧表示機能でシリアライザを新たに作成
- [x] ビューにて引数を変更
