### ISSUE TITLE
[野田の気持ち] Dockerでフロント動かせる環境作って欲しいなぁ

### ISSUE THREAD

**Issue by Hirochon** [Hirochon/Shappar#344]
2人で開発環境が手軽に合わせられるよ！笑

**Comment by fujiya228** [comment]
やるか、、、

**Comment by Hirochon** [comment]
ありがてえ🙏

**Comment by fujiya228** [comment]
`docker-compose up` で動くまでできたんやけど、ディレクトリ構成が原因でbuild したらstaticに反映されない状況

**Comment by fujiya228** [comment]
`docker-compose`ってコンテナのファイルは共有しない感じよね、、、？

**Comment by Hirochon** [comment]
docker-composeのservice単位でコンテナが分かれてるから、定義してるserviceが分かれていると、ファイルの共有はされない！

**Comment by fujiya228** [comment]
ですよねー
てか、`./static`ってどんな目的で使ってたっけ？
開発で必要ない（ビルドだけ）なら、frontのコンテナにだけ`./static`マウントすれば良いかも

**Comment by Hirochon** [comment]
用途は全く記憶にございません笑

**Comment by fujiya228** [comment]
他のサービスは`staticdata`でマウントしてるから問題なさそう（コードを反映しない点で）
