### ISSUE TITLE
.envのデフォルトファイル欲しい

### ISSUE THREAD

**Issue by fujiya228** [Hirochon/Shappar#359]
## 📝 関連issue / Related Issues

環境構築系

## :point_up: 背景 / Background

別のPCで動かそうとした時に環境変数がなくて動かなかった
他から取ってこようと思ったけどそもそもローカルで動かす分の環境変数はあっても良いと思った。

`.env.local`みたいなファイル作って、初期化時に`.env`にコピーする

```
cp .env.local .env
```

## ⛏ やること / ToDo

- [x] `.env.local`みたいなファイル作る
- [x] ~~クローンするときの説明に上記のコマンドを記述する~~

## 📸 スクリーンショット / Screenshots

**Comment by fujiya228** [comment]
@Hirochon どうすか？

**Comment by Hirochon** [comment]
Issueのテンプレも作ってたんや！ｗ
はさておき、

良い取り組みやと思いますよ〜 :smile:

**Comment by fujiya228** [comment]
やってみるっすー

**Comment by fujiya228** [comment]
> クローンするときの説明に上記のコマンドを記述する

は特になかったのでスキップ
