### ISSUE TITLE
Approveしなかったら、develop / masterへマージできない設定に変更

### ISSUE THREAD

**Issue by Hirochon** [Hirochon/Shappar#360]
## :point_up: 背景 / Background
ローカルでmaster / developへ直プッシュ出来ない状況を作ったのなら、
PRでapproveが無いとマージできない設定に変えたほうが、
「 **相手の許可がないと変更が出来ない** 」という状況がより作れると思う！

## ⛏ やること / ToDo

- [ ] Settingsで設定するだけ

## 📸 スクリーンショット / Screenshots

**Comment by Hirochon** [comment]
@fujiya228 
どうだろう

**Comment by fujiya228** [comment]
良いと思うっす！
ただ、pushできない状況があると嬉しいこととして、pushをトリガーとするActionが設定しやすいってのがあるっす！

**Comment by Hirochon** [comment]
なるるるるるるるるるるる！！！！

**Comment by Hirochon** [comment]
@fujiya228 
設定の詳細についてやけど、下記な感じの設定になっておりまふ

- `master` と `develop` のブランチに関してだけ、PRでmergeする前に許可を取る必要がある
- その許可は「**最低限一人には`approve`を貰わなければいけない**」というもの
- 他のブランチはどうにでもできる！

GitHub上で設定済みなので、確認したらCloseいたします！

**Comment by fujiya228** [comment]
@Hirochon 
確認しました！
あざます！
