### ISSUE TITLE
マイページのGET時にレスポンスする内容の確認

### ISSUE THREAD

**Issue by Hirochon** [Hirochon/Shappar#9]
![11333583949466](https://user-images.githubusercontent.com/50178851/73253184-5c58a280-41ff-11ea-8942-44a1ad1b7e5d.jpg)
### 想像してるマイページの簡易的なデザインもUPしました。
- [x] ユーザー情報の取得
    - UUID:str
    - ユーザID:str
    - ユーザ名:str
    - 紹介テキスト:str
    - IconURL:str
    - HomeImageURL:str
- [x] 過去の投稿の取得
    - Public実装後で
- [x] 過去の投票の取得
    - Public実装後で

**Comment by fujiya228** [comment]
OK！
いいと思う！

**Comment by Hirochon** [comment]
了解です。これでモデルを作成していきます。

**Comment by Hirochon** [comment]
画像のアップロード機能も追加するので、少し待っててね〜。

**Comment by fujiya228** [comment]
ユーザーの情報について整理して思ったんやけど、フォローワーあるならフォローあって良くない？
それと、フォローしているかどうか？フォローされているかどうか？
っていうのも、他人のページ表示する際にいるかも！

**Comment by Hirochon** [comment]
1.フォロー数表示関して
ユーザーがマイページを見たときに得れる情報無いし、表示する必要ないかなーっとおもってました！

2.他人のマイページで自分がフォローしているかどうかに関して
確かに表示する必要があると僕も思います！

3.他人のマイページにて自分がフォローされているかどうかに関して
1.をもし実装しないのであれば、3は必要が無くなってきます。

**Comment by fujiya228** [comment]
1.フォロー数表示関して
その数の部分から、その人のフォローしている人の一覧表示ページヘと飛ぶようにしようと思うんですが、いかがですか？

2.他人のマイページで自分がフォローしているかどうかに関して
じゃあ、表示する方向で

3.他人のマイページにて自分がフォローされているかどうかに関して
申し訳ないけど、1とのつながりがわからなかったです。

**Comment by fujiya228** [comment]
このサービスの方針として、匿名性にフォーカスすることがあるから、一旦フォローの機能はなしで実装しましょう！
というわけで、Privateページも見送りします！

**Comment by Hirochon** [comment]
同意見です。了解です👌
実装する要素(機能)一覧からフォロワー数欄を消しておきました！
